
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'dockerhubconn'
        repository: 'veerojuvenkatesh/venkydockerrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.BuildId)
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'azureserviceconn'
        appType: 'webAppContainer'
        WebAppName: 'venky-webapp-linux'
        DockerNamespace: 'veerojuvenkatesh/venkydockerrepo:latest'
        DockerRepository: 'veerojuvenkatesh/venkydockerrepo'
        DockerImageTag: 'latest'
        StartupCommand: 'java -jar  mybank.jar com.bank.BankApplication'
        

    